# Generated by Django 2.2.9 on 2020-01-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agresor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.CharField(max_length=50)),
                ('mes', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('nombre_victima', models.CharField(max_length=50)),
                ('nombre_acusado', models.CharField(max_length=50)),
                ('edad_acusado', models.CharField(max_length=50)),
                ('temperancia', models.CharField(max_length=50)),
                ('intento_suicidio', models.CharField(max_length=50)),
                ('relacion_victima', models.CharField(max_length=50)),
                ('sentencia', models.CharField(max_length=50)),
                ('fecha_sentencia', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'agresor',
            },
        ),
        migrations.CreateModel(
            name='Victima',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.CharField(max_length=50)),
                ('mes', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('nombre', models.CharField(max_length=50)),
                ('edad', models.CharField(max_length=50)),
                ('lugar', models.CharField(max_length=50)),
                ('provincia', models.CharField(max_length=50)),
                ('departamento', models.CharField(max_length=50)),
                ('geolocalizacion', models.CharField(max_length=50)),
                ('circunstancias', models.TextField()),
                ('agresion_previa', models.TextField()),
                ('causa_muerte', models.TextField()),
                ('numero_hijos', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'victima',
            },
        ),
    ]
