# Generated by Django 2.2.9 on 2020-01-20 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrevencionTool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agresor',
            name='estado_del_caso',
            field=models.CharField(default='nada', max_length=50),
        ),
        migrations.AddField(
            model_name='agresor',
            name='situacion_del_presunto_autor',
            field=models.CharField(default='nada', max_length=100),
        ),
        migrations.AddField(
            model_name='victima',
            name='estado_del_caso',
            field=models.CharField(default='nada', max_length=50),
        ),
        migrations.AddField(
            model_name='victima',
            name='situacion_del_presunto_autor',
            field=models.CharField(default='nada', max_length=100),
        ),
        migrations.AlterField(
            model_name='agresor',
            name='fecha',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='victima',
            name='fecha',
            field=models.CharField(max_length=50),
        ),
    ]
